
    var ProductPersonalAccidentModel = {
        ID : 0,
        ProductCode:"",
        CoverageCode:"",
        AssuredValue:"",
        AssuredBirthPlace:"",
        AssuredBirthday:"",
        AssuredOccupation:"",
        ProvinceCode:"",
        CityCode:"",
        PostalCode:"",
        Premi:"",
        DiscountPremi:"",
        TotalPremi:"",
        AssuredName:"",
        AssuredSex:"",
        AssuredAddress:"",
        AssuredRisk:"",
        AssuredEmail:"",
        AssuredPhone:"",
        AssuredStartDate:"",
        AssuredEndDate:"",
        Disclaimer:Boolean,
        Step:"",
        State:"",
        ReferenceNumber:"",
        PolicyNumber:"",
        CustomerID:"",
        AgentID:"",
        PolicyID:"",
        InvoiceURL:"",
        InvoiceExpiredDate:"",
        InvoiceID:"",
        PaymentAccountID:"",
        BeneficiariesModel:[],
        QuestionnaireModel:[],
        CreatedBy:"",
        CreatedOn:"",
        UpdatedBy:"",
        UpdatedOn:"",
        SubmittedBy:"",
        SubmittedOn:"",
        SurveyedBy:"",
        SurveyedOn:"",
        ReviewedBy:"",
        ReviewedOn:"",
        PaidBy:"",
        PaidOn:"",
        Note:""
    }

    export default ProductPersonalAccidentModel;