
    var SurveyorModel = {
        ID : 0,
        Name:"",
        Birthday:"",
        Sex:"",
        IdentificationNumber:"",
        IdentificationType:"",
        IdentificationName:"",
        SurveyorCode:"",
        DeviceID:"",
        Culture:"",
        State:"",
        Address:"",
        ProvinceCode:"",
        CityCode:"",
        SubDistrictCode:"",
        VillageCode:"",
        HamletCode:"",
        NeighbourhoodCode:"",
        PostalCode:"",
        Telephone:"",
        MobilePhone:"",
        MobilePhoneToken:"",
        MobilePhoneState:"",
        Email:"",
        EmailToken:"",
        EmailState:"",
        Password:"",
        PasswordNew:"",
        PasswordConfirmation:"",
        TaskTotal:"",
        TaskActive:"",
        TaskApproved:"",
        TaskRejected:"",
        ContractStartDate:"",
        ContractEndDate:"",
        BranchCode:"",
        BranchName:"",
        Count:0,
        CreatedBy:0,
        CreatedOn:"",
        UpdatedBy:0,
        UpdatedOn:"",
        LastLoginOn:""
    }

    export default SurveyorModel;